### ISSUE TITLE
Disable lisp-paredit unbalanced parentheses highlighting in the REPL.

### ISSUE THREAD

**Issue by jasongilman** [jasongilman/proto-repl#113]
Lisp Paredit will highlight sections with unbalanced parentheses in a red color. The Proto REPL REPL is a text editor with Clojure syntax highlighting and can often contain unbalance parentheses. See https://github.com/jonspalding/lisp-paredit/issues/20

The follow style should be used to disable this in the REPL.

``` LESS
.proto-repl-repl::shadow .lisp-syntax-error .region {
  background-color: rgba(0, 0, 0, 0) !important;
}
```
