### ISSUE TITLE
inline result unreadable in light syntax themes.

### ISSUE THREAD

**Issue by kzieli01** [jasongilman/proto-repl#115]
I'm using the One Light Syntax Theme and inline results still end up printed in dark in a dark box.

**Comment by jasongilman** [comment]
I took a look at this and it's all styled by [Atom ink](https://github.com/JunoLab/atom-ink). The latest code on master looks like it's doing the right thing https://github.com/JunoLab/atom-ink/blame/master/styles/ink.less#L90 That current release of Atom ink sets the background using some other value. The next release of ink should fix the problem. In the meantime you can add the following to you Atom styles.less which seems to fix the problem

``` Less
div .ink .tree  {
  background: contrast(@syntax-background-color,
                             darken(@syntax-background-color, 4%),
                             lighten(@syntax-background-color, 4%))
                    !important;
}
```
